In [2]:
from icecube import dataio

In [3]:
import sys
sys.path.insert(0, "/project/def-nahee/kbas/graphnet/src")

import graphnet

In [4]:
from graphnet.data.extractors.icecube import I3TruthExtractorPONE

graphnet [MainProcess] WARNING  2026-05-01 12:32:18 - <module> - `km3net` not available. Some functionality may be missing.

/home/kbas/.local/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

graphnet [MainProcess] WARNING  2026-05-01 12:39:06 - <module> - `jammy_flows` not available. Normalizing Flow functionality is missing.

In [5]:
DATA_PATH = "/home/kbas/scratch/Spring2026MC/Full_Geometry/with_first_three_steps/Muon_PMT_Response/muon_33939527_gen_001.i3.gz"
GCD_PATH = "/project/6008051/pone_simulation/GCD_Library/PONE_800mGrid_40mSpacing_40OMstring.i3.gz"

In [6]:
# my_truth_extractor = I3TruthExtractorPONE(mctree = 'I3MCTree_postprop'). aa bu yok yeni frame'lerdee

my_truth_extractor = I3TruthExtractorPONE(mctree = 'I3MCTree')

graphnet [MainProcess] INFO     2026-05-01 12:39:11 - I3TruthExtractorPONE.__init__ - Writing log to logs/graphnet_20260501-123911.log

In [7]:
my_truth_extractor._mctree

'I3MCTree'

In [8]:
my_truth_extractor._extend_boundary
## bunu bi dusun

0.0

In [9]:
my_truth_extractor._i3_file

''

In [10]:
my_truth_extractor._is_corsika
## bu nerden geliyo

False

In [11]:
my_truth_extractor._gcd_file

''

In [12]:
my_truth_extractor._gcd_dict

{}

In [13]:
my_truth_extractor._calibration

In [14]:
my_truth_extractor._extractor_name
## bu nerden geliyo

'truth'

In [15]:
my_truth_extractor._exclude
## bu nerden geliyo

[None]

In [16]:
my_truth_extractor.hull
## hmm

AttributeError: 'I3TruthExtractorPONE' object has no attribute 'hull'

In [17]:
my_truth_extractor.delaunay

AttributeError: 'I3TruthExtractorPONE' object has no attribute 'delaunay'

In [18]:
my_truth_extractor.set_gcd(i3_file=DATA_PATH, gcd_file=GCD_PATH)

In [19]:
my_truth_extractor._i3_file

'/home/kbas/scratch/Spring2026MC/Full_Geometry/with_first_three_steps/Muon_PMT_Response/muon_33939527_gen_001.i3.gz'

In [20]:
my_truth_extractor._gcd_file

'/project/6008051/pone_simulation/GCD_Library/PONE_800mGrid_40mSpacing_40OMstring.i3.gz'

In [21]:
my_truth_extractor._gcd_dict

In [22]:
my_truth_extractor._calibration

In [23]:
my_truth_extractor.hull

In [24]:
print(my_truth_extractor.hull)

<scipy.spatial._qhull.ConvexHull object at 0x14b6f022fad0>

In [25]:
my_truth_extractor.delaunay

In [26]:
print(my_truth_extractor.delaunay)

<scipy.spatial._qhull.Delaunay object at 0x14b67c41e4b0>

In [27]:
data_file = dataio.I3File(DATA_PATH)
frame = data_file.pop_physics()

In [28]:
my_truth_extractor(frame)

{'RunID': 1,
 'SubrunID': 4294967295,
 'EventID': 1,
 'SubEventID': 0,
 'position_x': 3319.2688054961113,
 'position_y': 749.5424208283403,
 'position_z': 1283.3862687237927,
 'pid': 14,
 'interaction_type': 1,
 'elasticity': 0.7754148929676531,
 'vertex_inside_detector_volume': False,
 'is_ending': -1,
 'totalEnergy': 30919.790319217227,
 'zenith': 1.1834652447389442,
 'azimuth': 0.2357774506086349,
 'finalStateX': 0.03487024977971519,
 'finalStateY': 0.22458510703234694,
 'finalType1': icecube._dataclasses.ParticleType.MuMinus,
 'finalType2': icecube._dataclasses.ParticleType.Hadrons,
 'initialType': icecube._dataclasses.ParticleType.NuMu,
 'totalColumnDepth': 707540.7451699107,
 'impactParameter': 107.496771030128,
 'EnergyMin': 100.0,
 'EnergyMax': 1000000.0,
 'ZenithMin': 0.0,
 'ZenithMax': 3.141592653589793,
 'AzimuthMin': 0.0,
 'AzimuthMax': 6.283185307179586,
 'PowerlawIndex': 1.5,
 'InjectionRadius': 1000.0,
 'EndcapLength': 1100.0,
 'CylinderRadius': -1,
 'CylinderHeight': -1}

In [29]:
electron_path = "/home/kbas/scratch/Spring2026MC/Full_Geometry/with_first_three_steps/Electron_PMT_Response/electron_33996141_gen_008.i3.gz"
muon_path = "/home/kbas/scratch/Spring2026MC/Full_Geometry/with_first_three_steps/Muon_PMT_Response/muon_33939527_gen_001.i3.gz"
tau_path = "/home/kbas/scratch/Spring2026MC/Full_Geometry/with_first_three_steps/Tau_PMT_Response/tau_33996158_gen_001.i3.gz"
NC_path = "/home/kbas/scratch/Spring2026MC/Full_Geometry/with_first_three_steps/NC_PMT_Response/nc_33996259_gen_001.i3.gz"

In [32]:
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [33]:
import pandas as pd
from icecube import icetray, dataio

paths = {
    "electron": electron_path,
    "muon":     muon_path,
    "tau":      tau_path,
    "NC":       NC_path,
}

rows = []
for flavor, path in paths.items():
    f = dataio.I3File(path)
    for frame in f:
        if frame.Stop == icetray.I3Frame.Physics:
            result = my_truth_extractor(frame)
            result["flavor"] = flavor
            rows.append(result)
            break
    f.close()

df = pd.DataFrame(rows).set_index("flavor")
df

,RunID,SubrunID,EventID,SubEventID,position_x,position_y,position_z,pid,interaction_type,elasticity,vertex_inside_detector_volume,is_ending,totalEnergy,zenith,azimuth,finalStateX,finalStateY,finalType1,finalType2,initialType,totalColumnDepth,impactParameter,EnergyMin,EnergyMax,ZenithMin,ZenithMax,AzimuthMin,AzimuthMax,PowerlawIndex,InjectionRadius,EndcapLength,CylinderRadius,CylinderHeight
flavor,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
electron,8,4294967295,1,0,-169.257211,-126.450342,-223.650534,12,1,0.244633,True,-1,166.314753,2.208915,0.587252,0.063154,0.755367,11,-2000001006,12,140139.185550,305.524186,100.0,1000000.0,0.0,3.141593,0.0,6.283185,1.5,-1.0,-1.0,900.0,1100.0
muon,1,4294967295,1,0,3319.268805,749.542421,1283.386269,14,1,0.775415,False,-1,30919.790319,1.183465,0.235777,0.034870,0.224585,13,-2000001006,14,707540.745170,107.496771,100.0,1000000.0,0.0,3.141593,0.0,6.283185,1.5,1000.0,1100.0,-1.0,-1.0
tau,1,4294967295,1,0,-588.165815,95.957702,-95.945473,16,1,0.685962,True,-1,3293.810462,2.917863,3.364710,0.325295,0.314038,15,-2000001006,16,112473.194140,563.605924,100.0,1000000.0,0.0,3.141593,0.0,6.283185,1.5,-1.0,-1.0,900.0,1100.0
NC,1,4294967295,1,0,246.850177,229.718643,184.583973,-12,2,0.856945,True,-1,344.955408,1.133893,4.906519,0.238655,0.143055,-12,-2000001006,-12,160417.098456,375.355022,100.0,1000000.0,0.0,3.141593,0.0,6.283185,1.5,-1.0,-1.0,900.0,1100.0

In [34]:
# the above cell is only one event per patch. below is everything:

In [40]:
import glob
import pandas as pd
from icecube import icetray, dataio

base_paths = {
    # "electron": "/home/kbas/scratch/String340MC/Full_Geometry/Electron_PMT_Response",
    "muon": "/home/kbas/scratch/Spring2026MC/Strings_102_40m/Muon_PMT_Response",
   # "NC":       "/home/kbas/scratch/String340MC/Full_Geometry/NC_PMT_Response",
    # "tau":      "/home/kbas/scratch/String340MC/Full_Geometry/Tau_PMT_Response",
}

rows = []
for flavor, base in base_paths.items():
    files = sorted(glob.glob(base + "/**/*.i3.gz", recursive=True))
    print(f"{flavor}: {len(files)} files found")
    for filepath in files:
        try:
            f = dataio.I3File(filepath)
            while f.more():
                frame = f.pop_daq()
                if frame is None:
                    continue
                result = my_truth_extractor(frame)
                result["flavor"] = flavor
                rows.append(result)
            f.close()
        except Exception as e:
            print(f"Error in {filepath}: {e}")
            continue

df = pd.DataFrame(rows)
print(f"Total events: {len(df)}")
df

muon: 50 files found
Total events: 710

,RunID,SubrunID,EventID,SubEventID,position_x,position_y,position_z,pid,interaction_type,elasticity,vertex_inside_detector_volume,is_ending,totalEnergy,zenith,azimuth,finalStateX,finalStateY,finalType1,finalType2,initialType,totalColumnDepth,impactParameter,EnergyMin,EnergyMax,ZenithMin,ZenithMax,AzimuthMin,AzimuthMax,PowerlawIndex,InjectionRadius,EndcapLength,CylinderRadius,CylinderHeight,flavor
0,1,4294967295,7,0,349.734821,410.070643,-558.261463,14,1,0.691455,False,-1,371.225428,1.953555,0.764692,0.178332,0.308545,13,-2000001006,14,4.591958e+05,322.101062,100.0,1000000.0,0.0,3.141593,0.0,6.283185,1.5,1000.0,1100.0,-1,-1,muon
1,1,4294967295,15,0,310.291074,84.733909,-349.644234,14,1,0.862388,True,-1,402.659959,0.388542,0.325324,0.464699,0.137612,13,-2000001006,14,4.735763e+05,430.037696,100.0,1000000.0,0.0,3.141593,0.0,6.283185,1.5,1000.0,1100.0,-1,-1,muon
2,1,4294967295,22,0,-622.893427,2193.307184,-2446.355605,14,1,0.572019,False,-1,88671.082944,2.453714,1.993016,0.049939,0.427981,13,-2000001006,14,2.485671e+06,381.176731,100.0,1000000.0,0.0,3.141593,0.0,6.283185,1.5,1000.0,1100.0,-1,-1,muon
3,1,4294967295,29,0,-1195.775143,-178.748548,-896.594636,14,1,0.871046,False,-1,2250.661884,1.934338,3.331335,0.185454,0.128954,13,-2000001006,14,9.406116e+05,411.485151,100.0,1000000.0,0.0,3.141593,0.0,6.283185,1.5,1000.0,1100.0,-1,-1,muon
4,1,4294967295,36,0,-3987.995862,-1836.814867,-1168.517538,-14,1,0.747881,False,-1,40345.618418,1.913116,3.578656,0.015317,0.252119,-13,-2000001006,-14,2.077699e+06,373.855033,100.0,1000000.0,0.0,3.141593,0.0,6.283185,1.5,1000.0,1100.0,-1,-1,muon
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705,1,4294967295,62,0,119.900221,3.320720,306.914950,-14,1,0.814415,True,-1,102.838197,1.340387,0.249990,0.188042,0.185585,-13,-2000001006,-14,2.742703e+05,273.367429,100.0,1000000.0,0.0,3.141593,0.0,6.283185,1.5,1000.0,1100.0,-1,-1,muon
706,1,4294967295,69,0,58.422415,363.641823,-222.421438,-14,1,0.787586,True,-1,131.593645,1.390336,2.126140,0.286123,0.212414,-13,-2000001006,-14,2.885644e+05,361.219355,100.0,1000000.0,0.0,3.141593,0.0,6.283185,1.5,1000.0,1100.0,-1,-1,muon
707,1,4294967295,71,0,-202.665395,-337.294648,-321.731248,-14,1,0.158673,True,-1,1454.902315,0.301913,2.410160,0.080734,0.841327,-13,-2000001006,-14,4.248540e+05,387.168895,100.0,1000000.0,0.0,3.141593,0.0,6.283185,1.5,1000.0,1100.0,-1,-1,muon
708,1,4294967295,72,0,-287.595250,1928.995517,-200.910223,-14,1,0.264825,False,-1,6205.061911,1.783711,1.684528,0.006932,0.735175,-13,-2000001006,-14,1.233770e+06,225.627204,100.0,1000000.0,0.0,3.141593,0.0,6.283185,1.5,1000.0,1100.0,-1,-1,muon
709,1,4294967295,85,0,-461.048205,250.493249,-98.951535,-14,1,0.734635,True,-1,270.722088,2.053932,1.879138,0.234806,0.265365,-13,-2000001006,-14,3.522623e+05,373.851345,100.0,1000000.0,0.0,3.141593,0.0,6.283185,1.5,1000.0,1100.0,-1,-1,muon

In [41]:
df.agg(['min', 'max'])

,RunID,SubrunID,EventID,SubEventID,position_x,position_y,position_z,pid,interaction_type,elasticity,vertex_inside_detector_volume,is_ending,totalEnergy,zenith,azimuth,finalStateX,finalStateY,finalType1,finalType2,initialType,totalColumnDepth,impactParameter,EnergyMin,EnergyMax,ZenithMin,ZenithMax,AzimuthMin,AzimuthMax,PowerlawIndex,InjectionRadius,EndcapLength,CylinderRadius,CylinderHeight,flavor
min,1,4294967295,1,0,-11090.838784,-23669.002911,-3221.640338,-14,1,0.008724,False,-1,100.116700,0.045345,0.006086,0.000210,0.002312,-13,-2000001006,-14,2.730896e+05,12.380755,100.0,1000000.0,0.0,3.141593,0.0,6.283185,1.5,1000.0,1100.0,-1,-1,muon
max,10,4294967295,100,0,88498.299157,10622.127852,58837.819582,14,1,0.997688,True,-1,995127.723722,3.121339,6.278441,0.760013,0.991276,13,-2000001006,14,3.600656e+06,741.453731,100.0,1000000.0,0.0,3.141593,0.0,6.283185,1.5,1000.0,1100.0,-1,-1,muon