In [1]:
from icecube import dataio

import pandas as pd

In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)

In [3]:
electron_weights = pd.read_csv("/project/def-nahee/kbas/Graphnet-Applications/Metadata/EventWeights/String340MC/Electron_LIW.csv")
muon_weights = pd.read_csv("/project/def-nahee/kbas/Graphnet-Applications/Metadata/EventWeights/String340MC/Muon_LIW.csv")
nc_weights = pd.read_csv("/project/def-nahee/kbas/Graphnet-Applications/Metadata/EventWeights/String340MC/NC_LIW.csv")
tau_weights = pd.read_csv("/project/def-nahee/kbas/Graphnet-Applications/Metadata/EventWeights/String340MC/Tau_LIW.csv")

In [4]:
electron_log = pd.read_csv("/home/kbas/scratch/String340MC/Logs/LIW/Electron_file_stats.csv")
muon_log = pd.read_csv("/home/kbas/scratch/String340MC/Logs/LIW/Muon_file_stats.csv")
tau_log = pd.read_csv("/home/kbas/scratch/String340MC/Logs/LIW/Tau_file_stats.csv")
nc_log = pd.read_csv("/home/kbas/scratch/String340MC/Logs/LIW/NC_file_stats.csv")

# I3 Files That Are Not Accesible At All

all of these should have 
- status = not_ok
- weights_calculated = 0
- and worths to check the error message
- also, these any of these files should not have any data in flavor_weights

bunlarin disinda da 0 olabilie btw

## Electron

In [5]:
len(electron_log[electron_log["i3_file_opened_ok"] == False])

8

In [6]:
electron_log[electron_log["i3_file_opened_ok"] == False]

,batch_id,lic_file,i3_file,status,error,i3_file_opened_ok,weights_calculated,duration_s
188,1080,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_1080.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_1080.i3.zst,not ok,i3 file problem: no DAQ frames with EventProperties and I3EventHeader were found in the EventProperties i3 file.,False,0,0.355621
805,1641,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_1641.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_1641.i3.zst,not ok,i3 file problem: no DAQ frames with EventProperties and I3EventHeader were found in the EventProperties i3 file.,False,0,0.291339
855,1687,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_1687.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_1687.i3.zst,not ok,i3 file problem: no DAQ frames with EventProperties and I3EventHeader were found in the EventProperties i3 file.,False,0,0.502012
2594,354,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_354.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_354.i3.zst,not ok,i3 file problem: no DAQ frames with EventProperties and I3EventHeader were found in the EventProperties i3 file.,False,0,0.812702
3759,5235,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_5235.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_5235.i3.zst,not ok,i3 file problem: no DAQ frames with EventProperties and I3EventHeader were found in the EventProperties i3 file.,False,0,0.116117
4543,6428,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_6428.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_6428.i3.zst,not ok,i3 file problem: no DAQ frames with EventProperties and I3EventHeader were found in the EventProperties i3 file.,False,0,0.548010
4676,6629,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_6629.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_6629.i3.zst,not ok,i3 file problem: no DAQ frames with EventProperties and I3EventHeader were found in the EventProperties i3 file.,False,0,0.248657
6631,9619,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_9619.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_9619.i3.zst,not ok,i3 file problem: no DAQ frames with EventProperties and I3EventHeader were found in the EventProperties i3 file.,False,0,0.206379

#### first idea is to check if these files are completely empthy.

In [ ]:
bad_electrons = electron_log.loc[
    electron_log["i3_file_opened_ok"] == False,
    "i3_file"
]

In [11]:
# check if there is any kind of frame:

for f in bad_electrons:
    i3 = dataio.I3File(f)

    if not i3.more():
        print("EMPTY:", f)
        i3.close()
        continue

    frame = i3.pop_frame()
    print("READ OK:", f, frame.Stop)

    i3.close()

EMPTY: /project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_1080.i3.zst
EMPTY: /project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_1641.i3.zst
EMPTY: /project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_1687.i3.zst
EMPTY: /project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_354.i3.zst
EMPTY: /project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_5235.i3.zst
EMPTY: /project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_6428.i3.zst
EMPTY: /project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_6629.i3.zst
EMPTY: /project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_9619.i3.zst

#### What kind of error message we get with this kind of files:

In [12]:

i3 = dataio.I3File("/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_1080.i3.zst"
)

print("opened")
print("more:", i3.more())

opened
more: False

In [13]:

frame = i3.pop_frame()

FATAL (dataio): no frame to pop (I3File.cxx:146 in I3FramePtr dataio::I3File::pop_frame(I3Frame::Stream))

RuntimeError: no frame to pop (in I3FramePtr dataio::I3File::pop_frame(I3Frame::Stream))

so these files should not be taken into account in anything. I added these files to paths.py

In [26]:
electron_log.loc[
    electron_log["i3_file_opened_ok"] == False,
    "batch_id"].isin(electron_weights["RunID"])

188     False
805     False
855     False
2594    False
3759    False
4543    False
4676    False
6631    False
Name: batch_id, dtype: bool

these problematic files are not in my event weight calculations, as it should not be.

In [27]:
electron_log = electron_log[electron_log["i3_file_opened_ok"] != False]

#### lets check if there are any other files that has no any event whose weight is calculated

In [28]:
electron_log[electron_log["weights_calculated"] == 0]

Empty DataFrame
Columns: [batch_id, lic_file, i3_file, status, error, i3_file_opened_ok, weights_calculated, duration_s]
Index: []

there is no. nice.

## Muon

In [ ]:
len(muon_log[muon_log["i3_file_opened_ok"] == False])

In [ ]:
muon_log[muon_log["i3_file_opened_ok"] == False]

## Tau

In [ ]:
len(tau_log[tau_log["i3_file_opened_ok"] == False])

In [ ]:
tau_log[tau_log["i3_file_opened_ok"] == False]

## NC

In [ ]:
len(nc_log[nc_log["i3_file_opened_ok"] == False])

In [ ]:
nc_log[nc_log["i3_file_opened_ok"] == False]

# I3 Files That Has < 200 & > 0 Available Events

In [ ]:
electron_log[
    (electron_log["weights_calculated"] > 0) &
    (electron_log["weights_calculated"] < 200)
]

In [ ]:
muon_log[
    (muon_log["weights_calculated"] > 0) &
    (muon_log["weights_calculated"] < 200)
]

In [ ]:
tau_log[
    (tau_log["weights_calculated"] > 0) &
    (tau_log["weights_calculated"] < 200)
]

In [ ]:
nc_log[
    (nc_log["weights_calculated"] > 0) &
    (nc_log["weights_calculated"] < 200)
]